# Generated by Django 3.2.4 on 2021-07-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='Photo')),
                ('title_sub', models.CharField(max_length=1000)),
                ('name_sub', models.CharField(max_length=1500)),
                ('code_sub', models.CharField(max_length=1500)),
                ('teacher', models.CharField(max_length=1500)),
            ],
        ),
    ]
