# Generated by Django 3.2.4 on 2021-07-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0002_subject_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_head',
            name='chapter_1',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
    ]
