# Generated by Django 3.2.4 on 2021-07-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0003_subject_head_chapter_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_head',
            name='chapter_10',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_head',
            name='chapter_11',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_head',
            name='chapter_2',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_head',
            name='chapter_3',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_head',
            name='chapter_4',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_head',
            name='chapter_5',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_head',
            name='chapter_6',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_head',
            name='chapter_7',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_head',
            name='chapter_8',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject_head',
            name='chapter_9',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
    ]
