# Generated by Django 3.2.4 on 2021-07-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0004_auto_20210702_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_head',
            name='verfify_score',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
    ]
