# Generated by Django 3.2.4 on 2021-07-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0005_subject_head_verfify_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sub', models.CharField(max_length=1500)),
                ('chapter_1', models.CharField(max_length=1500)),
                ('chapter_2', models.CharField(max_length=1500)),
            ],
        ),
    ]
