# Generated by Django 3.2.4 on 2021-07-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0006_chapter_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_head',
            name='chapter_1',
        ),
        migrations.RemoveField(
            model_name='subject_head',
            name='chapter_10',
        ),
        migrations.RemoveField(
            model_name='subject_head',
            name='chapter_11',
        ),
        migrations.RemoveField(
            model_name='subject_head',
            name='chapter_2',
        ),
        migrations.RemoveField(
            model_name='subject_head',
            name='chapter_3',
        ),
        migrations.RemoveField(
            model_name='subject_head',
            name='chapter_4',
        ),
        migrations.RemoveField(
            model_name='subject_head',
            name='chapter_5',
        ),
        migrations.RemoveField(
            model_name='subject_head',
            name='chapter_6',
        ),
        migrations.RemoveField(
            model_name='subject_head',
            name='chapter_7',
        ),
        migrations.RemoveField(
            model_name='subject_head',
            name='chapter_8',
        ),
        migrations.RemoveField(
            model_name='subject_head',
            name='chapter_9',
        ),
        migrations.RemoveField(
            model_name='subject_head',
            name='verfify_score',
        ),
        migrations.AddField(
            model_name='chapter_field',
            name='chapter_10',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter_field',
            name='chapter_11',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter_field',
            name='chapter_3',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter_field',
            name='chapter_4',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter_field',
            name='chapter_5',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter_field',
            name='chapter_6',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter_field',
            name='chapter_7',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter_field',
            name='chapter_8',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter_field',
            name='chapter_9',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter_field',
            name='verfify_score',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
    ]
