# Generated by Django 3.2.4 on 2021-07-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0007_auto_20210702_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_name_m_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1500)),
                ('last_name', models.CharField(max_length=1500)),
            ],
        ),
    ]
