# Generated by Django 3.2.4 on 2021-07-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0008_student_name_m_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_name_m_4',
            name='score_1',
            field=models.IntegerField(default=-1.0, max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_name_m_4',
            name='score_2',
            field=models.IntegerField(default=-1.0, max_length=110),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_name_m_4',
            name='score_3',
            field=models.IntegerField(default=-1.0, max_length=110),
            preserve_default=False,
        ),
    ]
