# Generated by Django 3.2.4 on 2021-07-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0009_auto_20210702_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter_content_m4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1500)),
                ('work', models.CharField(max_length=1500)),
            ],
        ),
    ]
