# Generated by Django 3.2.4 on 2021-07-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0010_chapter_content_m4'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter_content_m4',
            name='chapter_id',
            field=models.IntegerField(default=1, max_length=110),
            preserve_default=False,
        ),
    ]
