# Generated by Django 3.2.4 on 2021-07-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0013_remove_chapter_field_m4_verfify_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter_content_m4',
            name='chapter_id',
            field=models.CharField(max_length=110),
        ),
    ]
