# Generated by Django 3.2.4 on 2021-07-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0014_alter_chapter_content_m4_chapter_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter_field_m4',
        ),
        migrations.AddField(
            model_name='chapter_content_m4',
            name='chapter_name',
            field=models.CharField(default=-1.0, max_length=1500),
            preserve_default=False,
        ),
    ]
