# Generated by Django 3.2.4 on 2021-07-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0016_chapter_content_m4_lasttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design_Chapter_content_m5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.CharField(max_length=110)),
                ('chapter_name', models.CharField(max_length=1500)),
                ('content', models.CharField(max_length=1500)),
                ('work', models.CharField(max_length=1500)),
                ('lasttime', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Design_Student_name_m_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1500)),
                ('last_name', models.CharField(max_length=1500)),
                ('score_1', models.IntegerField(max_length=110)),
                ('score_2', models.IntegerField(max_length=110)),
                ('score_3', models.IntegerField(max_length=110)),
            ],
        ),
        migrations.DeleteModel(
            name='TablesNews',
        ),
    ]
