# Generated by Django 3.2.4 on 2021-07-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0017_auto_20210702_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_student_name_m_5',
            name='score_4',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AddField(
            model_name='design_student_name_m_5',
            name='score_5',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AddField(
            model_name='design_student_name_m_5',
            name='score_6',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AddField(
            model_name='design_student_name_m_5',
            name='score_7',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AddField(
            model_name='design_student_name_m_5',
            name='score_8',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AddField(
            model_name='design_student_name_m_5',
            name='score_9',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AddField(
            model_name='student_name_m_4',
            name='score_4',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AddField(
            model_name='student_name_m_4',
            name='score_5',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AddField(
            model_name='student_name_m_4',
            name='score_6',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AddField(
            model_name='student_name_m_4',
            name='score_7',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AddField(
            model_name='student_name_m_4',
            name='score_8',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AddField(
            model_name='student_name_m_4',
            name='score_9',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_1',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_2',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_3',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_1',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_2',
            field=models.IntegerField(default='0', max_length=110),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_3',
            field=models.IntegerField(default='0', max_length=110),
        ),
    ]
