# Generated by Django 3.2.4 on 2021-07-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0018_auto_20210702_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology_Chapter_content_m5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.CharField(max_length=110)),
                ('chapter_name', models.CharField(max_length=1500)),
                ('content', models.CharField(max_length=1500)),
                ('work', models.CharField(max_length=1500)),
                ('lasttime', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Technology_Student_name_m_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1500)),
                ('last_name', models.CharField(max_length=1500)),
                ('score_1', models.IntegerField(default='0', max_length=110)),
                ('score_2', models.IntegerField(default='0', max_length=110)),
                ('score_3', models.IntegerField(default='0', max_length=110)),
                ('score_4', models.IntegerField(default='0', max_length=110)),
                ('score_5', models.IntegerField(default='0', max_length=110)),
                ('score_6', models.IntegerField(default='0', max_length=110)),
                ('score_7', models.IntegerField(default='0', max_length=110)),
                ('score_8', models.IntegerField(default='0', max_length=110)),
                ('score_9', models.IntegerField(default='0', max_length=110)),
            ],
        ),
    ]
