# Generated by Django 3.2.4 on 2021-07-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0019_technology_chapter_content_m5_technology_student_name_m_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology_chapter_content_m5',
            name='content_video',
            field=models.CharField(default=-1, max_length=1500),
            preserve_default=False,
        ),
    ]
