# Generated by Django 3.2.4 on 2021-07-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0020_technology_chapter_content_m5_content_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology_chapter_content_m5',
            old_name='work',
            new_name='work_1',
        ),
        migrations.AddField(
            model_name='technology_chapter_content_m5',
            name='work_2',
            field=models.CharField(default=-1, max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology_chapter_content_m5',
            name='work_3',
            field=models.CharField(default=-2, max_length=1500),
            preserve_default=False,
        ),
    ]
