# Generated by Django 3.2.4 on 2021-07-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0021_auto_20210702_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology_chapter_content_m5',
            old_name='work_1',
            new_name='work',
        ),
        migrations.RemoveField(
            model_name='technology_chapter_content_m5',
            name='work_2',
        ),
        migrations.RemoveField(
            model_name='technology_chapter_content_m5',
            name='work_3',
        ),
    ]
