# Generated by Django 3.2.4 on 2021-07-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0022_auto_20210702_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter_content_m4',
            options={'verbose_name_plural': 'เนื้อหาวิชาออกแบบและเทคโนโลยี ม.4'},
        ),
        migrations.AlterModelOptions(
            name='design_chapter_content_m5',
            options={'verbose_name_plural': 'เนื้อหาวิชาออกแบบและเทคโนโลยี ม.5'},
        ),
        migrations.AlterModelOptions(
            name='design_student_name_m_5',
            options={'verbose_name_plural': 'รายชื่อนักเรียนวิชาออกแบบและเทคโนโลยี ม.5'},
        ),
        migrations.AlterModelOptions(
            name='student_name_m_4',
            options={'verbose_name_plural': 'รายชื่อนักเรียนวิชาออกแบบและเทคโนโลยี ม.4'},
        ),
        migrations.AlterModelOptions(
            name='subject_head',
            options={'verbose_name_plural': 'ข้อมูลวิชาทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='technology_chapter_content_m5',
            options={'verbose_name_plural': 'เนื้อหาวิชาเทคโนโลยี ม.5'},
        ),
        migrations.AlterModelOptions(
            name='technology_student_name_m_5',
            options={'verbose_name_plural': 'รายชื่อนักเรียนวิชาเทคโนโลยี ม.5'},
        ),
        migrations.RemoveField(
            model_name='technology_chapter_content_m5',
            name='content_video',
        ),
        migrations.AddField(
            model_name='design_chapter_content_m5',
            name='content_video',
            field=models.CharField(default=-1, max_length=1500, verbose_name='ลิงก์เนื้อหา วิดีโอ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter_content_m4',
            name='chapter_id',
            field=models.CharField(max_length=110, verbose_name='บทที่'),
        ),
        migrations.AlterField(
            model_name='chapter_content_m4',
            name='chapter_name',
            field=models.CharField(max_length=1500, verbose_name='ชื่อบท'),
        ),
        migrations.AlterField(
            model_name='chapter_content_m4',
            name='lasttime',
            field=models.CharField(max_length=1500, verbose_name='ระยะเวลา'),
        ),
        migrations.AlterField(
            model_name='design_chapter_content_m5',
            name='chapter_id',
            field=models.CharField(max_length=110, verbose_name='บทที่'),
        ),
        migrations.AlterField(
            model_name='design_chapter_content_m5',
            name='chapter_name',
            field=models.CharField(max_length=1500, verbose_name='ชื่อบท'),
        ),
        migrations.AlterField(
            model_name='design_chapter_content_m5',
            name='content',
            field=models.CharField(max_length=1500, verbose_name='ลิงก์เนื้อหา iframe'),
        ),
        migrations.AlterField(
            model_name='design_chapter_content_m5',
            name='lasttime',
            field=models.CharField(max_length=1500, verbose_name='ระยะเวลา'),
        ),
        migrations.AlterField(
            model_name='design_chapter_content_m5',
            name='work',
            field=models.CharField(max_length=1500, verbose_name='ลิงก์ใบงาน รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='first_name',
            field=models.CharField(max_length=1500, verbose_name='ชื่อจริง'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='last_name',
            field=models.CharField(max_length=1500, verbose_name='นามสกุล'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_1',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 1'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_2',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 2'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_3',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 3'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_4',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 4'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_5',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 5'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_6',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 6'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_7',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 7'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_8',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 8'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_9',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 9'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='first_name',
            field=models.CharField(max_length=1500, verbose_name='ชื่อจริง'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='last_name',
            field=models.CharField(max_length=1500, verbose_name='นามสกุล'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_1',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 1'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_2',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 2'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_3',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 3'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_4',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 4'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_5',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 5'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_6',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 6'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_7',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 7'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_8',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 8'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_9',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 9'),
        ),
        migrations.AlterField(
            model_name='technology_chapter_content_m5',
            name='chapter_id',
            field=models.CharField(max_length=110, verbose_name='บทที่'),
        ),
        migrations.AlterField(
            model_name='technology_chapter_content_m5',
            name='chapter_name',
            field=models.CharField(max_length=1500, verbose_name='ชื่อบท'),
        ),
        migrations.AlterField(
            model_name='technology_chapter_content_m5',
            name='lasttime',
            field=models.CharField(max_length=1500, verbose_name='ระยะเวลา'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='first_name',
            field=models.CharField(max_length=1500, verbose_name='ชื่อจริง'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='last_name',
            field=models.CharField(max_length=1500, verbose_name='นามสกุล'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_1',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 1'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_2',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 2'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_3',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 3'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_4',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 4'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_5',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 5'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_6',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 6'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_7',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 7'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_8',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 8'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_9',
            field=models.IntegerField(default='0', max_length=110, verbose_name='คะแนนที่ 9'),
        ),
    ]
