# Generated by Django 3.2.4 on 2021-07-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0023_auto_20210704_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter_content_m4',
            name='content_video',
            field=models.CharField(default='0', max_length=1500, verbose_name='ลิงก์เนื้อหา วิดีโอ'),
        ),
        migrations.AddField(
            model_name='technology_chapter_content_m5',
            name='content_video',
            field=models.CharField(default='0', max_length=1500, verbose_name='ลิงก์เนื้อหา วิดีโอ'),
        ),
        migrations.AlterField(
            model_name='chapter_content_m4',
            name='content',
            field=models.CharField(max_length=1500, verbose_name='ลิงก์เนื้อหา iframe'),
        ),
        migrations.AlterField(
            model_name='chapter_content_m4',
            name='work',
            field=models.CharField(max_length=1500, verbose_name='ลิงก์ใบงาน รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='design_chapter_content_m5',
            name='content_video',
            field=models.CharField(default='0', max_length=1500, verbose_name='ลิงก์เนื้อหา วิดีโอ'),
        ),
        migrations.AlterField(
            model_name='technology_chapter_content_m5',
            name='content',
            field=models.CharField(max_length=1500, verbose_name='ลิงก์เนื้อหา iframe'),
        ),
        migrations.AlterField(
            model_name='technology_chapter_content_m5',
            name='work',
            field=models.CharField(max_length=1500, verbose_name='ลิงก์ใบงาน รูปภาพ'),
        ),
    ]
