# Generated by Django 3.2.4 on 2021-07-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0024_auto_20210704_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology_chapter_content_m5',
            name='textwork',
            field=models.CharField(default=-1, max_length=1500, verbose_name='อธิบายใบงาน'),
            preserve_default=False,
        ),
    ]
