# Generated by Django 3.2.4 on 2021-07-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0026_auto_20210704_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_1',
            field=models.CharField(default='0', max_length=110, verbose_name='ผลงานที่เสร็จ 1.1'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_2',
            field=models.CharField(default='0', max_length=110, verbose_name='ผลงานที่เสร็จ 1.2'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_3',
            field=models.CharField(default='0', max_length=110, verbose_name='ผลงานที่เสร็จ 1.3'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_4',
            field=models.CharField(default='0', max_length=110, verbose_name='ผลงานที่เสร็จ 4'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_5',
            field=models.CharField(default='0', max_length=110, verbose_name='ผลงานที่เสร็จ 5'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_6',
            field=models.CharField(default='0', max_length=110, verbose_name='ผลงานที่เสร็จ 6'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_7',
            field=models.CharField(default='0', max_length=110, verbose_name='ผลงานที่เสร็จ 7'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_8',
            field=models.CharField(default='0', max_length=110, verbose_name='ผลงานที่เสร็จ 8'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_9',
            field=models.CharField(default='0', max_length=110, verbose_name='ผลงานที่เสร็จ 9'),
        ),
    ]
