# Generated by Django 3.2.4 on 2021-07-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0027_auto_20210704_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology_student_name_m_5',
            name='name_work_1',
            field=models.CharField(default='1', max_length=110, verbose_name='ใบงานที่'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_1',
            field=models.IntegerField(default='0', max_length=110, verbose_name=models.CharField(default='1', max_length=110, verbose_name='ใบงานที่')),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_1',
            field=models.CharField(default='0', max_length=110, verbose_name=models.CharField(default='1', max_length=110, verbose_name='ใบงานที่')),
        ),
    ]
