# Generated by Django 3.2.4 on 2021-07-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0030_auto_20210704_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sbmld_chapter_content_m6',
            options={'verbose_name_plural': 'เนื้อหาวิชา SBMLD ม.6'},
        ),
        migrations.AlterModelOptions(
            name='sbmld_student_name_m_6',
            options={'verbose_name_plural': 'รายชื่อนักเรียนวิชา SBMLD ม.6'},
        ),
        migrations.AddField(
            model_name='sbmld_chapter_content_m6',
            name='example_work',
            field=models.CharField(default=-1, max_length=1500, verbose_name='ลิงก์รูปตัวอย่าง'),
            preserve_default=False,
        ),
    ]
