# Generated by Django 3.2.4 on 2021-07-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0031_auto_20210704_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbmld_chapter_content_m6',
            name='chapter_id_work',
            field=models.IntegerField(default=-1, max_length=1500, verbose_name='ใบงานที่'),
            preserve_default=False,
        ),
    ]
