# Generated by Django 3.2.4 on 2021-07-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0032_sbmld_chapter_content_m6_chapter_id_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter_content_m4',
            name='chapter_name',
            field=models.CharField(max_length=500000000, verbose_name='ชื่อบท'),
        ),
        migrations.AlterField(
            model_name='chapter_content_m4',
            name='content',
            field=models.CharField(max_length=500000000, verbose_name='ลิงก์เนื้อหา iframe'),
        ),
        migrations.AlterField(
            model_name='chapter_content_m4',
            name='content_video',
            field=models.CharField(default='0', max_length=500000000, verbose_name='ลิงก์เนื้อหา วิดีโอ'),
        ),
        migrations.AlterField(
            model_name='chapter_content_m4',
            name='lasttime',
            field=models.CharField(max_length=500000000, verbose_name='ระยะเวลา'),
        ),
        migrations.AlterField(
            model_name='chapter_content_m4',
            name='work',
            field=models.CharField(max_length=500000000, verbose_name='ลิงก์ใบงาน รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='design_chapter_content_m5',
            name='chapter_name',
            field=models.CharField(max_length=500000000, verbose_name='ชื่อบท'),
        ),
        migrations.AlterField(
            model_name='design_chapter_content_m5',
            name='content',
            field=models.CharField(max_length=500000000, verbose_name='ลิงก์เนื้อหา iframe'),
        ),
        migrations.AlterField(
            model_name='design_chapter_content_m5',
            name='content_video',
            field=models.CharField(default='0', max_length=500000000, verbose_name='ลิงก์เนื้อหา วิดีโอ'),
        ),
        migrations.AlterField(
            model_name='design_chapter_content_m5',
            name='lasttime',
            field=models.CharField(max_length=500000000, verbose_name='ระยะเวลา'),
        ),
        migrations.AlterField(
            model_name='design_chapter_content_m5',
            name='work',
            field=models.CharField(max_length=500000000, verbose_name='ลิงก์ใบงาน รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='first_name',
            field=models.CharField(max_length=500000000, verbose_name='ชื่อจริง'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='last_name',
            field=models.CharField(max_length=500000000, verbose_name='นามสกุล'),
        ),
        migrations.AlterField(
            model_name='sbmld_chapter_content_m6',
            name='chapter_id_work',
            field=models.IntegerField(max_length=500000000, verbose_name='ใบงานที่'),
        ),
        migrations.AlterField(
            model_name='sbmld_chapter_content_m6',
            name='chapter_name',
            field=models.CharField(max_length=500000000, verbose_name='ชื่อบท'),
        ),
        migrations.AlterField(
            model_name='sbmld_chapter_content_m6',
            name='content',
            field=models.CharField(max_length=500000000, verbose_name='ลิงก์เนื้อหา iframe'),
        ),
        migrations.AlterField(
            model_name='sbmld_chapter_content_m6',
            name='content_video',
            field=models.CharField(default='0', max_length=500000000, verbose_name='ลิงก์เนื้อหา วิดีโอ'),
        ),
        migrations.AlterField(
            model_name='sbmld_chapter_content_m6',
            name='example_work',
            field=models.CharField(max_length=500000000, verbose_name='ลิงก์รูปตัวอย่าง'),
        ),
        migrations.AlterField(
            model_name='sbmld_chapter_content_m6',
            name='lasttime',
            field=models.CharField(max_length=500000000, verbose_name='ระยะเวลา'),
        ),
        migrations.AlterField(
            model_name='sbmld_chapter_content_m6',
            name='textwork',
            field=models.CharField(max_length=500000000, verbose_name='อธิบายใบงาน'),
        ),
        migrations.AlterField(
            model_name='sbmld_chapter_content_m6',
            name='work',
            field=models.CharField(max_length=500000000, verbose_name='ลิงก์ใบงาน รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='sbmld_student_name_m_6',
            name='first_name',
            field=models.CharField(max_length=500000000, verbose_name='ชื่อจริง'),
        ),
        migrations.AlterField(
            model_name='sbmld_student_name_m_6',
            name='last_name',
            field=models.CharField(max_length=500000000, verbose_name='นามสกุล'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='first_name',
            field=models.CharField(max_length=500000000, verbose_name='ชื่อจริง'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='last_name',
            field=models.CharField(max_length=500000000, verbose_name='นามสกุล'),
        ),
        migrations.AlterField(
            model_name='subject_head',
            name='code_sub',
            field=models.CharField(max_length=500000000),
        ),
        migrations.AlterField(
            model_name='subject_head',
            name='name_sub',
            field=models.CharField(max_length=500000000),
        ),
        migrations.AlterField(
            model_name='subject_head',
            name='teacher',
            field=models.CharField(max_length=500000000),
        ),
        migrations.AlterField(
            model_name='technology_chapter_content_m5',
            name='chapter_name',
            field=models.CharField(max_length=500000000, verbose_name='ชื่อบท'),
        ),
        migrations.AlterField(
            model_name='technology_chapter_content_m5',
            name='content',
            field=models.CharField(max_length=500000000, verbose_name='ลิงก์เนื้อหา iframe'),
        ),
        migrations.AlterField(
            model_name='technology_chapter_content_m5',
            name='content_video',
            field=models.CharField(default='0', max_length=500000000, verbose_name='ลิงก์เนื้อหา วิดีโอ'),
        ),
        migrations.AlterField(
            model_name='technology_chapter_content_m5',
            name='lasttime',
            field=models.CharField(max_length=500000000, verbose_name='ระยะเวลา'),
        ),
        migrations.AlterField(
            model_name='technology_chapter_content_m5',
            name='textwork',
            field=models.CharField(max_length=500000000, verbose_name='อธิบายใบงาน'),
        ),
        migrations.AlterField(
            model_name='technology_chapter_content_m5',
            name='work',
            field=models.CharField(max_length=500000000, verbose_name='ลิงก์ใบงาน รูปภาพ'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='first_name',
            field=models.CharField(max_length=500000000, verbose_name='ชื่อจริง'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='last_name',
            field=models.CharField(max_length=500000000, verbose_name='นามสกุล'),
        ),
    ]
