# Generated by Django 3.2.4 on 2021-07-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0034_auto_20210704_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbmld_chapter_content_m6',
            name='chapter_id_work',
            field=models.CharField(max_length=5000, verbose_name='ใบงานที่'),
        ),
    ]
