# Generated by Django 3.2.4 on 2021-07-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0036_auto_20210704_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_1',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 1'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_2',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 2'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_3',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 3'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_4',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 4'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_5',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 5'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_6',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 6'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_7',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 7'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_8',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 8'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_9',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 9'),
        ),
    ]
