# Generated by Django 3.2.4 on 2021-07-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0038_auto_20210704_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_1',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 1'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_2',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 2'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_3',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 3'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_4',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 4'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_5',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 5'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_6',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 6'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_7',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 7'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_8',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 8'),
        ),
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_9',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 9'),
        ),
        migrations.AlterField(
            model_name='sbmld_student_name_m_6',
            name='score_1',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 1'),
        ),
        migrations.AlterField(
            model_name='sbmld_student_name_m_6',
            name='score_2',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 2'),
        ),
        migrations.AlterField(
            model_name='sbmld_student_name_m_6',
            name='score_3',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 3'),
        ),
        migrations.AlterField(
            model_name='sbmld_student_name_m_6',
            name='score_4',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 4'),
        ),
        migrations.AlterField(
            model_name='sbmld_student_name_m_6',
            name='score_5',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 5'),
        ),
        migrations.AlterField(
            model_name='sbmld_student_name_m_6',
            name='score_6',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 6'),
        ),
        migrations.AlterField(
            model_name='sbmld_student_name_m_6',
            name='score_7',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 7'),
        ),
        migrations.AlterField(
            model_name='sbmld_student_name_m_6',
            name='score_8',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 8'),
        ),
        migrations.AlterField(
            model_name='sbmld_student_name_m_6',
            name='score_9',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 9'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_1',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 1'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_2',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 2'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_3',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 3'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_4',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 4'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_5',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 5'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_6',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 6'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_7',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 7'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_8',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 8'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_9',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนที่ 9'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_1',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 1'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_2',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 2'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_3',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 3'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_4',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 4'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_5',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 5'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_6',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 6'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_7',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 7'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_8',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 8'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_9',
            field=models.IntegerField(default='0', max_length=5000, verbose_name='คะแนนใบงานที่ 9'),
        ),
    ]
