# Generated by Django 3.2.4 on 2021-07-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0043_auto_20210723_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_7',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 5.3'),
        ),
    ]
