# Generated by Django 3.2.4 on 2021-08-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0044_alter_design_student_name_m_5_score_7'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_student_name_m_5',
            name='score_finalterm',
            field=models.IntegerField(default='0', verbose_name='คะแนนสอบปลายภาค'),
        ),
        migrations.AddField(
            model_name='design_student_name_m_5',
            name='score_midterm',
            field=models.IntegerField(default='0', verbose_name='คะแนนสอบกลางภาค'),
        ),
        migrations.AddField(
            model_name='sbmld_student_name_m_6',
            name='score_finalterm',
            field=models.IntegerField(default='0', verbose_name='คะแนนสอบปลายภาค'),
        ),
        migrations.AddField(
            model_name='sbmld_student_name_m_6',
            name='score_midterm',
            field=models.IntegerField(default='0', verbose_name='คะแนนสอบกลางภาค'),
        ),
        migrations.AddField(
            model_name='student_name_m_4',
            name='score_finalterm',
            field=models.IntegerField(default='0', verbose_name='คะแนนสอบปลายภาค'),
        ),
        migrations.AddField(
            model_name='student_name_m_4',
            name='score_midterm',
            field=models.IntegerField(default='0', verbose_name='คะแนนสอบกลางภาค'),
        ),
        migrations.AddField(
            model_name='technology_student_name_m_5',
            name='score_finalterm',
            field=models.IntegerField(default='0', verbose_name='คะแนนสอบปลายภาค'),
        ),
        migrations.AddField(
            model_name='technology_student_name_m_5',
            name='score_midterm',
            field=models.IntegerField(default='0', verbose_name='คะแนนสอบกลางภาค'),
        ),
    ]
