# Generated by Django 3.2.4 on 2021-08-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0045_auto_20210820_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_2',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 2.1'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_3',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 2.2'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_4',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 3.1'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_5',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 3.2'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_6',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 4.1'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_7',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 4.2'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_finalterm',
            field=models.IntegerField(default='0', verbose_name='คะแนนปลายภาค'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_midterm',
            field=models.IntegerField(default='0', verbose_name='คะแนนกลางภาค'),
        ),
    ]
