# Generated by Django 3.2.4 on 2021-08-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0046_auto_20210820_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_finalterm',
            field=models.IntegerField(default='0', verbose_name='คะแนนสอบปลายภาค'),
        ),
        migrations.AlterField(
            model_name='student_name_m_4',
            name='score_midterm',
            field=models.IntegerField(default='0', verbose_name='คะแนนสอบกลางภาค'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='name_work_1',
            field=models.TextField(default='1.1', max_length=5000, verbose_name='ใบงานที่ 1.1'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='name_work_2',
            field=models.TextField(default='1.2', max_length=5000, verbose_name='ใบงานที่ 1.2'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='name_work_3',
            field=models.TextField(default='1.3', max_length=5000, verbose_name='ใบงานที่ 1.3'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='name_work_4',
            field=models.TextField(default='2.1', max_length=5000, verbose_name='ใบงานที่ 2.1'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='name_work_5',
            field=models.TextField(default='2.2', max_length=5000, verbose_name='ใบงานที่ 2.2'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='name_work_6',
            field=models.TextField(default='2.3', max_length=5000, verbose_name='ใบงานที่ 2.3'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_1',
            field=models.IntegerField(default='0', verbose_name='คะแนนใบงานที่ 1.1'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_2',
            field=models.IntegerField(default='0', verbose_name='คะแนนใบงานที่ 1.2'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_3',
            field=models.IntegerField(default='0', verbose_name='คะแนนใบงานที่ 1.3'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_4',
            field=models.IntegerField(default='0', verbose_name='คะแนนใบงานที่ 2.1'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_5',
            field=models.IntegerField(default='0', verbose_name='คะแนนใบงานที่ 2.2'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='score_6',
            field=models.IntegerField(default='0', verbose_name='คะแนนใบงานที่ 2.3'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_1',
            field=models.TextField(default='0', max_length=5000, verbose_name='ผลงานที่เสร็จ 1.1'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_2',
            field=models.TextField(default='0', max_length=5000, verbose_name='ผลงานที่เสร็จ 1.2'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_3',
            field=models.TextField(default='0', max_length=5000, verbose_name='ผลงานที่เสร็จ 1.3'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_4',
            field=models.TextField(default='0', max_length=5000, verbose_name='ผลงานที่เสร็จ 2.1'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_5',
            field=models.TextField(default='0', max_length=5000, verbose_name='ผลงานที่เสร็จ 2.2'),
        ),
        migrations.AlterField(
            model_name='technology_student_name_m_5',
            name='work_success_student_6',
            field=models.TextField(default='0', max_length=5000, verbose_name='ผลงานที่เสร็จ 2.3'),
        ),
    ]
