# Generated by Django 3.2.6 on 2021-09-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyWebsite', '0047_auto_20210820_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_student_name_m_5',
            name='score_8',
            field=models.IntegerField(default='0', verbose_name='คะแนนที่ 5.4'),
        ),
    ]
